apiVersion: apps/v1
kind: Deployment
metadata:
  name: susdcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: susdcs
  template:
    metadata:
      labels:
        app: susdcs
    spec:
      containers:
      - image: okteto.dev/yuftfray:latest
        name: susdcs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9058159c-d101-4fa6-bc84-6daf2c9cfbe4"
        - name: Vless_Path
          value: "/vless555"
        - name: Vmess_UUID
          value: "9058159c-d101-4fa6-bc84-6daf2c9cfbe4"
        - name: Vmess_Path
          value: "/vmess666"
        - name: Share_Path
          value: "/v2link"
